name: 3dscene
channels:
  - conda-forge
dependencies:
 - affine=2.3.1
 - asttokens=2.0.5
 - attrs=21.4.0
 - backcall=0.2.0
 - backports=1.0
 - backports.functools_lru_cache=1.6.4
 - blosc=1.21.1
 - boost-cpp=1.74.0
 - brotlipy=0.7.0
 - bzip2=1.0.8
 - ca-certificates=2022.6.15
 - cairo=1.16.0
 - certifi=2022.6.15
 - cffi=1.15.0
 - cfitsio=4.1.0
 - charset-normalizer=2.0.12
 - click=8.1.3
 - click-plugins=1.1.1
 - cligj=0.7.2
 - colorama=0.4.5
 - cryptography=37.0.2
 - curl=7.83.1
 - debugpy=1.6.0
 - decorator=5.1.1
 - entrypoints=0.4
 - executing=0.8.3
 - expat=2.4.8
 - font-ttf-dejavu-sans-mono=2.37
 - font-ttf-inconsolata=3.000
 - font-ttf-source-code-pro=2.038
 - font-ttf-ubuntu=0.83
 - fontconfig=2.14.0
 - fonts-conda-ecosystem=1
 - fonts-conda-forge=1
 - freetype=2.10.4
 - freexl=1.0.6
 - geos=3.10.3
 - geotiff=1.7.1
 - gettext=0.19.8.1
 - hdf4=4.2.15
 - hdf5=1.12.1
 - icu=70.1
 - idna=3.3
 - ipykernel=6.15.0
 - ipython=8.4.0
 - jedi=0.18.1
 - jpeg=9e
 - jupyter_client=7.3.4
 - jupyter_core=4.10.0
 - kealib=1.4.14
 - krb5=1.19.3
 - lcms2=2.12
 - lerc=3.0
 - libblas=3.9.0
 - libcblas=3.9.0
 - libcurl=7.83.1
 - libdeflate=1.12
 - libffi=3.4.2
 - libgdal=3.5.0
 - libglib=2.70.2
 - libiconv=1.16
 - libkml=1.3.0
 - liblapack=3.9.0
 - libnetcdf=4.8.1
 - libpng=1.6.37
 - libpq=14.4
 - librttopo=1.1.0
 - libsodium=1.0.18
 - libspatialite=5.0.1
 - libssh2=1.10.0
 - libtiff=4.4.0
 - libwebp-base=1.2.2
 - libxml2=2.9.14
 - libzip=1.8.0
 - libzlib=1.2.12
 - lz4-c=1.9.3
 - matplotlib-inline=0.1.3
 - mbutil=0.3.0
 - mkl=2022.1.0
 - nest-asyncio=1.5.5
 - numpy=1.22.4
 - openjpeg=2.4.0
 - openssl=1.1.1o
 - packaging=21.3
 - parso=0.8.3
 - pcre=8.45
 - pickleshare=0.7.5
 - pip=22.1.2
 - pixman=0.40.0
 - poppler=22.04.0
 - poppler-data=0.4.11
 - postgresql=14.4
 - proj=9.0.1
 - prompt-toolkit=3.0.29
 - psutil=5.9.1
 - pure_eval=0.2.2
 - pycparser=2.21
 - pygments=2.12.0
 - pyopenssl=22.0.0
 - pyparsing=3.0.9
 - pyproj=3.3.1
 - pysocks=1.7.1
 - pystac=1.4.0
 - pystac-client=0.4.0
 - python=3.10.5
 - python-dateutil=2.8.2
 - python_abi=3.10
 - pyzmq=23.1.0
 - rasterio=1.2.10
 - requests=2.28.0
 - setuptools=62.6.0
 - six=1.16.0
 - snappy=1.1.9
 - snuggs=1.4.7
 - sqlite=3.38.5
 - stack_data=0.3.0
 - tbb=2021.5.0
 - tiledb=2.9.5
 - tk=8.6.12
 - tornado=6.1
 - traitlets=5.3.0
 - tzdata=2022a
 - urllib3=1.26.9
 - wcwidth=0.2.5
 - wheel=0.37.1
 - xerces-c=3.2.3
 - xz=5.2.5
 - zeromq=4.3.4
 - zlib=1.2.12
 - zstd=1.5.2
 - pip:
    - osm2geojson==0.2.0
